/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class swe574_boun_edu_androidproject_tools_AndroidUtilities */

#ifndef _Included_swe574_boun_edu_androidproject_tools_AndroidUtilities
#define _Included_swe574_boun_edu_androidproject_tools_AndroidUtilities
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     swe574_boun_edu_androidproject_tools_AndroidUtilities
 * Method:    loadBitmap
 * Signature: (Ljava/lang/String;Landroid/graphics/Bitmap;IIII)V
 */
JNIEXPORT void JNICALL Java_swe574_boun_edu_androidproject_tools_AndroidUtilities_loadBitmap
  (JNIEnv *, jclass, jstring, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
